### ISSUE TITLE
runCmd hangs indefinitely

### ISSUE THREAD

**Issue by am11** [wfurt/freebsd-bootstrap-cli#1]
​

**Comment by wfurt** [comment]
Can you modify it to use `ssh -v ...`. That should show some output. 
I don't care much how we do this e.g. `vagrant` is fine by me as long as it is easy to use and does not suck in too many dependencies. I also wanted to run it under double emulation e.g. FreeBSD running as VM on my MacBook and that limited some options. I had fragments of logic with QEMU from some other work so it was convenient to reuse.   
Maybe if we split logic to create tools (currently unfinished) from orchestration (QEMU, vagrant, ...???)it may be path forward. I did not have much time recently to push this forward ;(

**Comment by am11** [comment]
`ssh -vvv` output:

```ssh
[vagrant@bazinga ~/freebsd-bootstrap-cli]$ ssh -vvv root@127.0.0.1 -p 8022 -i artifacts/sshKeys ls
OpenSSH_7.8p1, OpenSSL 1.1.1a-freebsd  20 Nov 2018
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug2: ssh_connect_direct
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 8022.
debug1: Connection established.
debug1: identity file artifacts/sshKeys type 0
debug1: identity file artifacts/sshKeys-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8 FreeBSD-20180909
```
(hangs here indefinitely.. for hours)

vagrant supports various providers (virtualbox, vmware, libvirt, hyperv..), we can try using the slimmer one: libvirt.

I was also running it under the CI: https://cirrus-ci.com/build/6005915073642496, which gives different error (at `ssh-keygen` / `ssh-keyscan` steps), because that session is running under root by default. We can add a user in wheel group, but if vagrant can cleanly replace it we can focus on next steps. Will add "publish to github releases on tag push", once <kbd>product-build_script</kbd> succeed.

**Comment by am11** [comment]
Upd: vagrant option failed also due to lack of nested virtualization support in the VM I was using as well as CirrusCI. I have taken a different approach for CirrusCI, by using interdependent tasks; crossgen on Linux, native compilation on FreeBSD, collect and push artifacts to GitHub releases. Trying to figure out cleaner way for intermediate share: https://github.com/cirruslabs/cirrus-ci-docs/issues/558.

**Comment by wfurt** [comment]
What versions do you use @am11? I'll try to reproduce or figure out why it hangs. I know QEMU is slow but it seems like the least amount of dependencies for anybody to try. I'll try to find some time over the weekend.

**Comment by am11** [comment]
@wfurt, it would be great if it works in any virtual environment with qemu without needing to have VT-x enabled.

I am running [`generic/freebsd12`](https://app.vagrantup.com/generic/boxes/freebsd12) vagrant box in Ubuntu 18.04 (Azure VM with nested Virtualization enabled). In that (nested) VM, I am unable to get qemu or vagrant+virtualbox to work successfully. `qemu` hangs and vagrant complains about no VT-x support. In VagrantFile, I even tried enabling nested virtualization in FreeBSD VM using:

```rb
Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd12"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end
...
```

but `dmesg -a` still shows no VT-x support:

```
...
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2302.79-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x406f1  Family=0x6  Model=0x4f  Stepping=1
  Features=0x1783fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,HTT>
  Features2=0x1a0201<SSE3,SSSE3,PCID,SSE4.1,SSE4.2>
  AMD Features=0x28100800<SYSCALL,NX,RDTSCP,LM>
  AMD Features2=0x1<LAHF>
  Structured Extended Features=0x2401<FSGSBASE,INVPCID,NFPUSG>
...
```

which, as per [this thread](https://forums.freebsd.org/threads/how-do-you-check-to-see-if-hyper-v-is-enabled-using-console.64164/), should contain line similar to:

```
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID
```

**Comment by wfurt** [comment]
it seems like this was runtime bug.
